nameOverride: ""

service:
  type: LoadBalancer
  httpPort: 80 
  wsPort: 4327

rconWeb:
  username: admin
  passwordExistingSecret: minecraft-rcon-creds
  passwordKey: web-admin-password
  game: minecraft
  serverName: minecraft-minecraft
  rconHost: minecraft-minecraft-rcon
  rconPort: 25575
  rconPasswordExistingSecret: minecraft-rcon-creds
  rconPasswordKey: rcon-password
  isAdmin: true
  websocketUrl: ""
  websocketUrlSsl: ""

persistence:
  enabled: false
