---
apiVersion: v2
name: minecraft
description: Minecraft server Helm chart
type: application
version: 5.1.2
appVersion: "latest"
keywords:
  - game
  - minecraft
sources:
  - https://itzg.github.io/minecraft-server-charts/
